### ISSUE TITLE
Could states sent to/from server be signed or encrypted?

### ISSUE THREAD

**Issue by xvoidsquadx** [tobyink/p5-story-interact#2]

**Comment by tobyink** [comment]
That makes sense

**Comment by atealltheberries** [comment]
Will this be implemented?

**Comment by tobyink** [comment]
Oh yeah, sorry, forgot about this. I did work on a OFB CAST5 encrypted dump/load for Story::Interact::State. It seems to work but I didn't have a lot of time to test it.

You set `PERL_STORY_INTERACT_KEY` environment variable on the server and once it's set, all dumped story states will be encrypted with that key. (The key needs to be a string 5 to 16 characters long.)

The state loader will decrypt any encrypted states, but will also continue to load older unencrypted states. You can set a `PERL_STORY_INTERACT_FORCE_ENCRYPTED` environment variable to 1 to forbid loading any unencrypted states.

I'll try to release a new version of Story::Interact some time today. Story::Interact::WWW doesn't need any changes. You just need to make sure the web server can see those environment variables.

**Comment by xvoidsquadx** [comment]
Thank you!
